########################################
# Workflow for checking terraform code
name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: infra

permissions:
  contents: read

env:
  environment: prod

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Az CLI
        run: |
          az login -u ${{ secrets.AZURE_CRED_U }} -p ${{ secrets.AZURE_CRED_P }} &>/dev/null
          az version

      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        id: init
        run: terraform init -backend=false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file=./infra_variables/${{ env.environment }}.tfvars

  checkov:
    name: Checkov Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkov Scan
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        continue-on-error: true
        with:
          framework: terraform
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload SARIF file
        id: checkov-upload
        uses: github/codeql-action/upload-sarif@v2
        # Results are generated only on a success or failure
        if: success() || failure()
        with:
          sarif_file: results.sarif

  terrascan:
    name: Terrascan Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Terrascan Scan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: "terraform"
          iac_version: "v14"
          policy_type: "azure"
          only_warn: true
          sarif_upload: true

      - name: Upload SARIF file
        id: terrascan-upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: terrascan.sarif
