########################################
# Workflow for checking terraform code
name: Put name here
run-name: ${{ github.actor }} run this action

on:
  push:
    branches:
      - none

env:
  work_dir: infra

jobs:
  install-terraform:
    name: Install Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing Terraform
        id: tf_install
        uses: hashicorp/setup-terraform@v2
        with:
          terraform-version: latest

      - name: Terraform Init
        id: init
        run: terraform init -backend=false
        working-directory: ${{ env.work_dir }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ${{ env.work_dir }}
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: terraform Validate -no-color
        working-directory: ${{ env.work_dir }}
