########################################
# Workflow for checking terraform code
name: Terraform Plan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  pull_request_review:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: infra

permissions:
  contents: read

jobs:
  # Terraform Job
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure
      - name: Az CLI
        run: |
          az login -u ${{ secrets.AZURE_CRED_U }} -p ${{ secrets.AZURE_CRED_P }} &>/dev/null
          az version

      # Installing Terraform
      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Terraform Init
      - name: Terraform Init
        id: init
        run: terraform init

      # Terraform Format
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      # Terraform Validate
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var '${{ secrets.SSH }}' -var-file 'infra_variables/prod.tfvars'

  # # Checkov Job
  # checkov:
  #   name: Checkov Scan
  #   runs-on: ubuntu-latest
  #   permissions:
  #     security-events: write

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     # Checkov Scan
  #     - name: Checkov Scan
  #       id: checkov
  #       uses: bridgecrewio/checkov-action@v12
  #       continue-on-error: true
  #       with:
  #         framework: terraform
  #         # This will create a checkov.sarif file
  #         output_format: sarif
  #         output_file_path: checkov.sarif

  #     # Upload Checkov Scan
  #     - name: Upload SARIF file
  #       id: checkov-upload
  #       uses: github/codeql-action/upload-sarif@v2
  #       # Results are generated only on a success or failure
  #       if: success() || failure()
  #       with:
  #         sarif_file: checkov.sarif

  # Terrascan Job
  terrascan:
    name: Terrascan Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Terrascan Scan
      - name: Terrascan Scan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: terraform
          iac_version: v14
          policy_type: azure
          only_warn: true
          sarif_upload: true

      # Upload Terrascan Scan
      - name: Upload SARIF file
        id: terrascan-upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: terrascan.sarif
